// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtuoeckmidmczktmowqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dW9lY2ttaWRtY3prdG1vd3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDc1NzgsImV4cCI6MjA2OTE4MzU3OH0.O1UCVvu6rmBqdIpUbz1ce-L6HtdZWnZQD1eNYrTpN3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});